### ISSUE TITLE
Missing files for Azure

### ISSUE THREAD

**Issue by piotrwozniak28** [fivetran/benchmark#7]
Blobs for Azure seem to be missing. Would you mind checking that out?

e.g. 
https://github.com/fivetran/benchmark/blob/master/500-PopulateAzure.sql line **613**:
[https://fivetranbenchmark.blob.core.windows.net/tpcds/tpcds_1000_dat/web_sales/](https://fivetranbenchmark.blob.core.windows.net/tpcds/tpcds_1000_dat/web_sales/)

EDIT:
I was able to populate some of the tables. I'm assuming that other are fine as well. My bad. Must've had an improper SSMS connection setting.

**Comment by georgewfraser** [comment]
Azure is unmaintained at this point. We don't have enough customers using it to be comfortable benchmarking it. It's possible we could screw something up and not realize it.
