### ISSUE TITLE
Json command not found

### ISSUE THREAD

**Issue by aberrantCode** [fivetran/benchmark#9]
Trying to reproduce this for BigQuery and am executing [this script](https://github.com/fivetran/benchmark/blob/master/401-BenchmarkBigQuery.sh), but am running into an issue with the "json" command not being found.  Tried aliasing jq to json but that didn't work.  Anyone know how to install that package?

**Comment by georgewfraser** [comment]
You need to install https://www.npmjs.com/package/json
